set_global_assignment -name SYSTEMVERILOG_FILE ../mistery_top.sv
set_global_assignment -name VERILOG_FILE ../mist/sigma_delta_dac.v
set_global_assignment -name QIP_FILE ../mist/mist.qip
set_global_assignment -name VERILOG_FILE ../mist/data_io.v
set_global_assignment -name QIP_FILE ../mist/vidclkcntrl.qip
set_global_assignment -name QIP_FILE ../atarist/atarist.qip
set_global_assignment -name SDC_FILE ../MiSTery.sdc
set_global_assignment -name QIP_FILE ../DeMiSTify/controller/controller.qip
set_global_assignment -name VHDL_FILE ../demistify_config_pkg.vhd
set_global_assignment -name VHDL_FILE ../firmware/controller_rom1_byte.vhd
set_global_assignment -name VHDL_FILE ../firmware/controller_rom2_byte.vhd
