M48
; DRILL file {KiCad (6.0.0)} date Tue Mar 22 13:40:29 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-22T13:40:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X150.483Y-82.535
X155.333Y-82.535
T2
X150.183Y-79.505
X155.633Y-79.505
T0
M30
